name: Mark Kirkpatrick
markdown: kramdown

baseurl:  /mkirkpat.github.io
permalink: /blog/:year/:month/:day/:title

paginate: 5
paginate_path: "blog/:num"

gems:
  - jekyll-last-modified-at

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      subheading: "Test holder"
