name: Mark Kirkpatrick
markdown: kramdown

baseurl:  /mkirkpat.github.io
permalink: /blog/:year/:month/:day/:title

paginate: 5
paginate_path: "blog/:num"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      subtitle: "Test holder"
